"""
Django settings for TeaFarmGIS project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os 

#==========================================Setting gdal library path=====================================================
GDAL_LIBRARY_PATH = os.getenv('GDAL_LIBRARY_PATH', r'C:\Users\alber\Envs\codedreamer\Lib\site-packages\osgeo\gdal305.dll') 
os.environ['GEOS_LIBRARY_PATH'] = r'C:\OSGeo4W\bin'

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9t=()4$6!z$q94w6w9n3d!pm_fja!1^t7c%s^@p#7e2q^utc#g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'leaflet',
    'sol',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#=====================================Enabling CORS====================================
CORS_ALLOW_ALL_ORIGINS = True

#----------------------------------------------

ROOT_URLCONF = 'TeaFarmGIS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TeaFarmGIS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'taifaorbit',
        'USER': 'postgres',
        'PASSWORD': '6479Abcd4489-',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#==========================CUSTOMIZING BACKEND MAPS WITH LEAFLET===================================
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (-0.1, 35.3),
    'DEFAULT_ZOOM': 10,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 20,
    'SCALE': 'both',
    'ATTRIBUTION_PREFIX': 'TeaFarmGIS',
    'TILES': [
        # OpenStreetMap
        ('OpenStreetMap',
         'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
         {'attribution': '&copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'}),

        # Google Streets (note: unofficial, usage not guaranteed by Google)
        ('Google Streets',
         'http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
         {
             'attribution': '&copy; <a href="https://maps.google.com">Google</a>',
             'subdomains': ['mt0', 'mt1', 'mt2', 'mt3']
         }),

        # Google Satellite
        ('Google Satellite',
         'http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
         {
             'attribution': '&copy; <a href="https://maps.google.com">Google</a>',
             'subdomains': ['mt0', 'mt1', 'mt2', 'mt3']
         }),

        # Google Hybrid (satellite + labels)
        ('Google Hybrid',
         'http://{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',
         {
             'attribution': '&copy; <a href="https://maps.google.com">Google</a>',
             'subdomains': ['mt0', 'mt1', 'mt2', 'mt3']
         }),
    ]
}
